### ISSUE TITLE
Reflect Cluster Configuration

### ISSUE THREAD

**Issue by gambol99** [appvia/kore-ui#65]
It would be nice to reflect visually somehow what has been configured in regard to the cluster i.e. the security features and options which has been enabled .. Referring to https://github.com/appvia/kore/blob/master/doc/security-gke.md

**Comment by gambol99** [comment]
cc @lewismarshall

**Comment by davet1985** [comment]
Shouldn't this be something that is coming from the API? I don't think we would want to hard-code this as features could be disabled/amended and then the UI would be showing incorrect information.

**Comment by davet1985** [comment]
Spoken to @gambol99, `wontfix` as this will be placed into plans.
