### ISSUE TITLE
Make the team name consistent via the UI / CLI 

### ISSUE THREAD

**Issue by gambol99** [appvia/kore-ui#66]
## As a developer who created a team

I didn't realise that the name of the team had dashes in it, (as i created spaces) and wasn't able to authenticate as my team name had "-"'s but in the gui it didn't.

**Comment by davet1985** [comment]
This would mean that the user would need to name the team using a k8s friendly name. This means the name might not be as descriptive.

How about we retain the summary, but display the "name" (k8s friendly name) and explain when that should be used?

**Comment by davet1985** [comment]
As discussed in planning, we will expose the "id" of the team on the UI so that the user will know what to expect when looking at the CLI

**Comment by gambol99** [comment]
Confirmed as done .. I can see from the UI user is given feedback as to the cli name and the team id is present in the team page. Perhaps a display help on hover? ... This will also be made easier when we place teams in the profile perhaps ... Marking as done for now as the rest are different stories
