### ISSUE TITLE
Namespace Names conflict across multiple clusters in a team

### ISSUE THREAD

**Issue by gambol99** [appvia/kore-ui#69]
So most resources in the team namespace use the resource name i.e. `metadata.name`; namespaces are slightly different though as we can't use the name of the resource as you might (and probably will) use the same name for a namespace across cluster. i.e. you have app1 on dev and prod clusters. The namespace resource has a `.spec.name` which should be used for namespace name (indeed the controller uses that) .. the resource name should probably be cluster+name

**Comment by asmith030** [comment]
I've tested this:
```
adam_smith@cloudshell:~ (appvia-hub)$ kubectl -n adam get namespaceclaims
NAME             AGE
adam-one-clash   118s
adam-two-clash   111s
```
LGTM
