### ISSUE TITLE
Error when trying to create a team with a new user

### ISSUE THREAD

**Issue by bandesz** [appvia/kore-ui#74]
## What

I get a "An error occurred creating the team, please try again" error when I try to create a team with a new user.

## Error

```
Error making request to API with path /teams/aaa 403 Request failed with status code 403
```

## How to reproduce

1. Log in with a completely new user
1. You won't be in any teams and the only action you can do is to create a team
1. When you try to create a team you will get the "An error occurred creating the team, please try again" error.

**Comment by davet1985** [comment]
This is an issue with the API, see https://github.com/appvia/kore/pull/133

**Comment by davet1985** [comment]
Since appvia/kore#133 has now been merged, I've brought this issue straight into QA.

**Comment by bandesz** [comment]
Tested, I can create teams with admin/non-admin users.
