### ISSUE TITLE
UI renders incorrectly the when user navigates to the team page

### ISSUE THREAD

**Issue by bandesz** [appvia/kore-ui#75]
## What

1. The user gets invited to a team
1. As the new member of the team I click on the team link. e.g. http://localhost:3000/teams/a-team
1. The UI doesn't render correctly
1. When I refresh the page the UI renders correctly

## Screenshot

<img width="1536" alt="Screenshot 2020-03-09 at 10 33 22" src="https://user-images.githubusercontent.com/868104/76205189-a5821600-61f1-11ea-8603-e6f42401d706.png">

**Comment by davet1985** [comment]
This is a dev issue only, something to do with the order the styles are applied.

To fix in dev, reload the page from the server, using CMD+R or browser refresh button.

In production, the next app is built and run in prod mode meaning this does not happen.
