### ISSUE TITLE
when we use korectl local configure the api already has the gke credentials

### ISSUE THREAD

**Issue by lewismarshall** [appvia/kore-ui#78]
The setup screen shouldn't prompt for cloud credentials if they already exist in the API

@ezodude @davet1985 FYI

**Comment by davet1985** [comment]
@lewismarshall the UI will check for GKE credentials created by the `kore-admin` team. If any exist it will not prompt for them to be created so this shouldn't be happening.

Are you able to confirm if this is still an issue?

**Comment by lewismarshall** [comment]
Yep can confirm this just worked (just tested `korectl local`)

**Comment by davet1985** [comment]
> Yep can confirm this just worked (just tested `korectl local`)

Thanks for checking 👍
