### ISSUE TITLE
Error requesting team after session timeout

### ISSUE THREAD

**Issue by davet1985** [appvia/kore-ui#91]
If you have an expired session and try to request a team page by clicking the left-side menu you get the following error.

It can be replicated as follows:
- sign-in and navigate to a team
- open dev console and clear page cookies
- click the team name button on the left-side menu

This is related to the requests being done on the client-side.

<img width="1062" alt="Screen Shot 2020-03-18 at 10 03 52" src="https://user-images.githubusercontent.com/1334068/76949628-bd981a80-6900-11ea-9be3-33faaaef2c6f.png">

**Comment by gambol99** [comment]
So i did the above, should the result of this be i'm redirected back the login screen? (which makes sense) ..

**Comment by davet1985** [comment]
> So i did the above, should the result of this be i'm redirected back the login screen? (which makes sense) .. in which case i can mark it as done

Yes login screen is correct. There's no session there to try and re-auth with the IDP so the user must login again.

**Comment by gambol99** [comment]
In which case I can mark this as 'done' ... boom
